### ISSUE TITLE
Implementar extractor de archivos separados por comas

### ISSUE THREAD

**Issue by haxdai** [RepositorioNacionalCultura/Harvester#3]
Implementar extractor de archivos CSV que reciba una ruta a un archivo y devuelva la información en un formato intermedio para realizar la transformación y mapeo de valores. La ruta al archivo podrá ser remota o local.
  
- [ ] Definir el formato predeterminado de columnas
- [ ] Implementar extractor transformando la estructura de acuerdo con las columnas

**Comment by haxdai** [comment]
@jafdeza Éste es el código de ejemplo: https://github.com/FST2015PM/Plataforma/blob/master/src/main/java/org/fst2015pm/swbforms/extractors/CSVExtractor.java#L29

**Comment by jafdeza** [comment]
Se implementó el extractor que soporta archivos csv
